name: sm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '5.6','7.0','7.1', '7.2', '7.4', '8.0' ]
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Check PHP Version
        run: php -v && php -i | grep opcache
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute tests
        run: ./vendor/bin/phpunit --colors=always
